layout_spectrum: 0.20612493576481938
typography_spectrum: 0.495344519848004
color:
  brandStrength: 0.8712194920517504
  lightness: 0.15750729502178729
  saturation: 0.9867095539811999
  rhythmicContrast: 0.14220438641496003
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
name: All INN
